-- 1. 시퀀스 생성 (수동 호출용)
CREATE SEQUENCE DTEAM.BOOK_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE CACHE 20;

CREATE SEQUENCE DTEAM.MEMBER_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE CACHE 20;

CREATE SEQUENCE DTEAM.OVERDUE_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE CACHE 20;

CREATE SEQUENCE DTEAM.RENTAL_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE CACHE 20;

-- 2. 테이블 생성 (시스템 생성 시퀀스/인덱스 방지)
-- BOOK 테이블
CREATE TABLE "DTEAM"."BOOK" (
    "BOOKID" NUMBER(10, 0) NOT NULL,
    "REGNO" VARCHAR2(50 CHAR) NOT NULL,
    "TITLE" VARCHAR2(1024 CHAR) NOT NULL,
    "AUTHOR" VARCHAR2(512 CHAR) NOT NULL,
    "PUBLISHER" VARCHAR2(512 CHAR) NOT NULL,
    "PUBLISHDATE" DATE NOT NULL,
    "ISBN" VARCHAR2(30 CHAR) NOT NULL,
    "KDC" VARCHAR2(20 CHAR) NOT NULL,
    "DDC" VARCHAR2(20 CHAR) NOT NULL,
    "RENTSTATUS" VARCHAR2(1) NOT NULL,
    "REGDATE" DATE NOT NULL,
    CONSTRAINT "CK_BOOK_RENTSTATUS" CHECK (RentStatus IN ('Y', 'N')),
    CONSTRAINT "PK_BOOK_BOOKID" PRIMARY KEY ("BOOKID"), -- PK 명칭 지정
    CONSTRAINT "UK_BOOK_REGNO" UNIQUE ("REGNO")        -- UK 명칭 지정
) TABLESPACE "USERS";

-- MEMBER 테이블
CREATE TABLE "DTEAM"."MEMBER" (
    "MEMBERID" NUMBER(10, 0) NOT NULL,
    "USERID" VARCHAR2(50) NOT NULL,
    "USERPASS" VARCHAR2(25) NOT NULL,
    "USERNAME" VARCHAR2(50) NOT NULL,
    "USERPHONE" VARCHAR2(20) NOT NULL,
    "USEROVERDUESTATE" VARCHAR2(1) DEFAULT 'N' NOT NULL,
    "REGDATE" DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT "CK_MEMBER_USEROVERDUESTATE" CHECK (UserOverdueState IN ('Y', 'N')),
    CONSTRAINT "PK_MEMBER_MEMBERID" PRIMARY KEY ("MEMBERID"),
    CONSTRAINT "UK_MEMBER_USERID" UNIQUE ("USERID")
) TABLESPACE "USERS";

-- OVERDUE 테이블 (IDENTITY 제거)
CREATE TABLE "DTEAM"."OVERDUE" (
    "OVERDUEID" NUMBER(10, 0) NOT NULL, -- 시스템 시퀀스 생성 방지
    "MEMBERID" NUMBER(10, 0) NOT NULL,
    "OVERDUESTARTDATE" DATE NOT NULL,
    "OVERDUERELEASEDATE" DATE DEFAULT sysdate + 14 NOT NULL,
    "OVERDUESTATUS" VARCHAR2(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT "CK_OVERDUE_OVERDUESTATUS" CHECK (OverdueStatus IN ('R', 'C', 'O')),
    CONSTRAINT "PK_OVERDUE_OVERDUEID" PRIMARY KEY ("OVERDUEID")
) TABLESPACE "USERS";

-- RENTAL 테이블
CREATE TABLE "DTEAM"."RENTAL" (
    "RENTALID" NUMBER(10, 0) NOT NULL,
    "MEMBERID" NUMBER(10, 0) NOT NULL,
    "BOOKID" NUMBER(10, 0) NOT NULL,
    "RENTDATE" DATE NOT NULL,
    "RETURNDUEDATE" DATE NOT NULL,
    "RETURNDATE" DATE NOT NULL,
    "RENTALSTATUS" VARCHAR2(1) DEFAULT 'R' NOT NULL,
    CONSTRAINT "CK_RENTAL_RENTALSTATUS" CHECK (RentalStatus IN ('R', 'C', 'O')),
    CONSTRAINT "PK_RENTAL_ID_COMP" PRIMARY KEY ("RENTALID", "MEMBERID", "BOOKID")
) TABLESPACE "USERS";

-- 3. 추가 인덱스 생성 및 주석
COMMENT ON COLUMN DTEAM.RENTAL.RENTALSTATUS IS '대출된 도서의 상태(R=대출중, C=반납완료, O=연체중)';

-- Oracle Text Index (이것은 도서 검색 기능을 위해 유지)
CREATE INDEX "DTEAM"."IDX_BOOK_TITLE" ON "DTEAM"."BOOK" ("TITLE") INDEXTYPE IS "CTXSYS"."CONTEXT";

-- 마지막으로 휴지통 정리
PURGE RECYCLEBIN;
